routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Manajemen\DokterController;
use App\Http\Controllers\Manajemen\JadwalPasienController;
use App\Http\Controllers\Manajemen\KeuanganController;
use App\Http\Controllers\Manajemen\ObatController;
use App\Http\Controllers\Manajemen\PasienController;
use App\Http\Controllers\Manajemen\PerawatController;
use App\Http\Controllers\Manajemen\RekamMedisController;
use App\Http\Controllers\Manajemen\{UserController, AkunController};
use App\Http\Controllers\PemeriksaanController;
use App\Http\Controllers\PendaftaranController;
use App\Models\Rekam_medis;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login', 301);

Route::get('login',         [AuthController::class, 'index'])->name('login');
Route::post('login',        [AuthController::class, 'login'])->name('loginPost');


Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard',                   [HomeController::class, 'index'])->name('home');
    Route::get('logout',                      [AuthController::class, 'logout'])->name('logout');

    Route::get('/antrian/delete/{id}',        [HomeController::class, 'antriandelete'])->name('home.antrian.delete');
    Route::middleware(['olah_pasien'])->group(function () {
        // Route Sub-menu Pendaftaran
        Route::get('pendaftaran',                 [PendaftaranController::class, 'index'])->name('pendaftaran.index');
        Route::post('pendaftaran/new',            [PendaftaranController::class, 'storenew'])->name('pendaftaran.baru');
        Route::post('pendaftaran/old',            [PendaftaranController::class, 'storeold'])->name('pendaftaran.lama');
    });

    Route::get('/pemeriksaan',                [PemeriksaanController::class, 'index'])->name('pemeriksaan.index');


    Route::prefix('manajemen')->group(function () {
        Route::middleware(['olah_rekmed'])->group(function () {
            Route::get('/rekam-medis',               [RekamMedisController::class, 'index'])->name('manajemen.rm');
            Route::get('/rekam-medis/show/{id}',     [RekamMedisController::class, 'show'])->name('manajemen.rm.show');
            Route::get('/rekam-medis/edit/{id}',     [RekamMedisController::class, 'edit'])->name('manajemen.rm.edit');
            Route::post('/rekam-medis/store',        [RekamMedisController::class, 'store'])->name('manajemen.rm.store');
            Route::post('/rekam-medis/add/obat',     [ObatController::class, 'addtorekmed'])->name('manajemen.rm.add.obat');
        });

        Route::get('/jadwal-pasien',             [JadwalPasienController::class, 'index'])->name('manajemen.jadwalpasien');
        Route::get('/jadwal-pasien/{id}',             [JadwalPasienController::class, 'search'])->name('manajemen.jadwalpasien.show');

        Route::middleware(['olah_obat'])->group(function () {
            Route::get('/obat',                      [ObatController::class, 'index'])->name('manajemen.obat');
            Route::post('/obat/update',              [ObatController::class, 'update'])->name('manajemen.obat.update');
            Route::post('/obat/store',               [ObatController::class, 'store'])->name('manajemen.obat.store');
            Route::post('/obat/riwayat-update',      [ObatController::class, 'index_riwayat'])->name('manajemen.obat.rirwayat');
            Route::get('/pasien',                    [PasienController::class, 'index'])->name('manajemen.pasien');
            Route::post('/pasien/edit',              [PasienController::class, 'edit'])->name('manajemen.pasien.edit');
        });
        Route::middleware(['superadmin'])->group(function () {
            Route::get('/perawat',                   [PerawatController::class, 'index'])->name('manajemen.perawat');
            Route::post('/perawat/store',            [PerawatController::class, 'store'])->name('manajemen.perawat.store');
            Route::get('/perawat/delete/{id}',           [PerawatController::class, 'delete'])->name('manajemen.perawat.delete');

            Route::get('/dokter',                    [DokterController::class, 'index'])->name('manajemen.dokter');
            Route::post('/dokter/store',             [DokterController::class, 'store'])->name('manajemen.dokter.store');
            Route::get('/dokter/delete/{id}',            [DokterController::class, 'delete'])->name('manajemen.dokter.delete');
        });
        Route::middleware(['olah_keuangan'])->group(function () {
            Route::get('/keuangan',                  [KeuanganController::class, 'index'])->name('manajemen.keuangan');
            Route::post('/keuangan/update',          [KeuanganController::class, 'update'])->name('manajemen.keuangan.update');
        });

        Route::prefix('akun')->group(function () {
            Route::middleware(['superadmin'])->group(function () {
                Route::resource('manajemen-akun',         UserController::class)->except('create', 'show');
            });
            Route::get('ganti-password',             [AkunController::class, 'gantiPassword'])->name('akun.ganti-password');
            Route::patch('ganti-password',           [AkunController::class, 'updatePassword'])->name('akun.ganti-password');
            Route::get('profil',                     [AkunController::class, 'profil'])->name('akun.profil');
        });
    });


    // //template test
    // Route::get('rekam-medis/lihat-rm', function () {
    //     return view('/rekam-medis/lihat-rm');
    // });


    // Route::get('pemeriksaan/lihat-pemeriksaan', function () {
    //     return view('pemeriksaan/lihat-pemeriksaan');
    // });

    // Route::get('rekam-medis/edit-rm', function () {
    //     return view('rekam-medis/edit-rm');
    // });

    // Route::get('/profile', function () {
    //     return view('master/profile');
    // });

    // Route::get('/ganti-password', function () {
    //     return view('master/ganti-password');
    // });

    // Route::group(['middleware'=>'Role:superadmin'], function (){
    //     Route::get()
    // });

    // Route::group(['middleware'=>'Role:customerservice'], function (){
    //     Route::get()
    // });

    // Route::group(['middleware'=>'Role:perawat'], function (){
    //     Route::get()
    // });
    // Route::group(['middleware'=>'Role:dokter'], function (){
    //     Route::get()
    // });

});

resources/views/partial/footer.blade.php
<footer class="footer text-center"> 2021 &copy; TIM 08 </footer>

resources/views/partial/menu.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">


            <li class="nav-small-cap m-t-10"></li>
            <li> <a href="{{Route('home')}}" class="waves-effect"><i class="ti-home p-r-10"></i> <span
                        class="hide-menu ">Beranda</span></a> </li>
            @can('olah_pasien')
            <li> <a href="{{Route('pendaftaran.index')}}" class="waves-effect"><i class="fa fa-user-plus p-r-10"></i>
                    <span class="hide-menu"> Pendaftaran </span></a>
            @endcan
            <li> <a href="{{Route('pemeriksaan.index')}}" class="waves-effect"><i class="fa fa-stethoscope p-r-10"></i>
                    <span class="hide-menu"> Pemeriksaan </span></a>
            </li>

            <li> <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-hospital-o p-r-10"></i>
                    <span class="hide-menu"> Manajemen <span class="fa arrow"></span></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{Route('manajemen.pasien')}}"><i class="fa fa-users"></i> Pasien </a></li>
                    @can('olah_obat')
                        <li><a href="{{Route('manajemen.obat')}}"><i class="fa fa-plus-square"></i> Obat </a></li>
                    @endcan
                    @can('olah_rekmed')
                        <li><a href="{{Route('manajemen.rm')}}"><i class="fa fa-book"></i> Rekam Medis </a></li>
                    @endcan
                    <li><a href="{{Route('manajemen.jadwalpasien')}}"><i class="fa fa-calendar-plus-o"></i> Jadwal
                            Pasien </a>
                    </li>
                    @can('superadmin')
                        <li><a href="{{Route('manajemen.dokter')}}"><i class="fa fa-user-md"></i> Dokter </a></li>
                        <li><a href="{{Route('manajemen.perawat')}}"><i class="fa fa-user-plus"></i> Perawat </a></li>
                    @endcan
                    @can('olah_keuangan')
                    <li><a href="{{Route('manajemen.keuangan')}}"><i class="fa fa-money"></i> Keuangan </a></li>
                    @endcan
                </ul>
            </li>
            <li> <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-user p-r-10"></i> <span
                        class="hide-menu"> Akun <span class="fa arrow"></span></span></a>
                <ul class="nav nav-second-level">
                    @can('superadmin')
                    <li><a href="{{ route('manajemen-akun.index') }}"><i class="icon-people"></i> Manajemen Akun
                        </a>
                    </li>
                    @endcan
                    <li><a href="{{ route('akun.profil') }}"><i class="fa fa-user"></i> Profile </a></li>
                    <li><a href="{{ route('akun.ganti-password') }}"><i class="fa fa-key"></i> Ganti Password </a></li>
                </ul>
            </li>
            <li class="nav-small-cap m-t-10"></li>
            <li><a href="/logout" class="waves-effect "><i class="icon-logout fa-fw"></i> <span class="hide-menu">Log
                        out</span></a></li>

        </ul>
    </div>
</div>

resources/views/partial/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" href="images/icons/favicon.ico" />

resources/views/partial/navigation.blade.php
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)"
            data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <div class="top-left-part bg-white"><a class="logo hidden-xs" href="{{route('home')}}"><b><img
                        src="/images/LSHC_Side.png" alt="lampungsporthealth" /></b><span class="hidden-xs"></span></a>
        </div>
        <ul class="nav navbar-top-links navbar-right pull-right">


            <!-- /.User Kanan -->
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <img
                        src="{{Auth::user()->photo}}" onerror="this.onerror=null; this.src='{{asset('plugins/images/users/d1.jpg')}}'" alt="../plugins/images/users/d1.jpg" width="36" class="img-circle"><b
                        class="hidden-xs">{{Auth::user()->nama}}</b> </a>

                <!-- /.User Kanan -->
            </li>

        </ul>
    </div>
</nav>